package br.com.x10d.monitorsinais.model;

import java.util.HashMap;

public class MnemonicoLista {

	HashMap<String, Mnemonico> lista; 
	
	public Mnemonico devolveDescricao(String chave) {
		
		return lista.get(chave);
	}	

	public MnemonicoLista() {
		
		lista = new HashMap<String, Mnemonico>();

		lista.put("5WREF", new Mnemonico("Abertura de 5ª Roda Recusada ", "Evento", "Normal", "5WREF"));
		lista.put("BOEVT", new Mnemonico("Abertura de Baú ", "Evento", "Normal", "BOEVT"));
		lista.put("EXDOO", new Mnemonico("Abertura de Porta com Ignição Ligada ", "Evento", "Alarme", "EXDOO"));
		lista.put("RDOPN", new Mnemonico("Abertura de Porta Direita ", "Evento", "Normal", "RDOPN"));
		lista.put("LDOPN", new Mnemonico("Abertura de Porta Esquerda ", "Evento", "Normal", "LDOPN"));
		lista.put("DOIOF", new Mnemonico("Abertura de Portas ", "Evento", "Normal", "DOIOF"));
		lista.put("BOPDN", new Mnemonico("Abertura/Fechamento Recusado - Baú controlado pelo Cavalo ", "Evento", "Normal", "BOPDN"));
		lista.put("EXAON", new Mnemonico("Alarme Configurável 1", "Evento", "Alarme", "EXAON"));
		lista.put("EXATW", new Mnemonico("Alarme Configurável 2", "Evento", "Alarme", "EXATW"));
		lista.put("EXATH", new Mnemonico("Alarme Configurável 3", "Evento", "Alarme", "EXATH"));
		lista.put("EXAFO", new Mnemonico("Alarme Configurável 4", "Evento", "Alarme", "EXAFO"));
		lista.put("ACTV", new Mnemonico("Alerta de Ativação", "Evento", "Alerta", "ACTV"));
		lista.put("EPSC", new Mnemonico("Alimentação Externa Conectada ", "Evento", "Normal", "EPSC"));
		lista.put("EPSD", new Mnemonico("Alimentação Externa Desconectada ", "Evento", "Alerta", "EPSD"));
		lista.put("GPSRE", new Mnemonico("Antena de GPS Reconectada Evento", "Evento", "Evento", "GPSRE"));
		lista.put("GPSRC", new Mnemonico("Antena GPS Reconectada ", "Evento", "Normal", "GPSRC"));
		lista.put("ANTON", new Mnemonico("Antifurto Alarmado ", "Evento", "Alarme", "ANTON"));
		lista.put("ANTOF", new Mnemonico("Antifurto Normalizado", "Evento", "Evento", "ANTOF"));
		lista.put("EXBBI", new Mnemonico("Arrombamento de Baú ", "Evento", "Alarme", "EXBBI"));
		lista.put("ACTTU", new Mnemonico("Atualização de Teste de Comunicação Celular ", "Evento", "Normal", "ACTTU"));
		lista.put("FWCCU", new Mnemonico("Atualização de Versão do Controlador de Carga ", "Evento", "Normal", "FWCCU"));
		lista.put("VBREC", new Mnemonico("Bateria do Veículo Reconectada ", "Evento", "Evento", "VBREC"));
		lista.put("NBOK", new Mnemonico("Bateria Interna do Rastreador OK ", "Evento", "Normal", "NBOK"));
		lista.put("BOTTR", new Mnemonico("Baú aberto pelo Rastreador do Cavalo ", "Evento", "Alerta", "BOTTR"));
		lista.put("BULKC", new Mnemonico("Baú Deslacrado pela Central ", "Evento", "Alerta", "BULKC"));
		lista.put("BLKCT", new Mnemonico("Baú Lacrado pela Central ", "Evento", "Alerta", "BLKCT"));
		lista.put("BLKDV", new Mnemonico("Baú Lacrado pelo Motorista ", "Evento", "Alerta", "BLKDV"));
		lista.put("EXRBL", new Mnemonico("Bloqueio Remoto ", "Evento", "Alarme", "EXRBL"));
		lista.put("BOEVB", new Mnemonico("Bloqueio: Abertura de Baú ", "Evento", "Alarme", "BOEVB"));
		lista.put("EXDOB", new Mnemonico("Bloqueio: Abertura de Porta com Ignição Ligada ", "Evento", "Alarme", "EXDOB"));
		lista.put("EXAOB", new Mnemonico("Bloqueio: Alarme Configurável 1", "Evento", "Alarme", "EXAOB"));
		lista.put("EXABW", new Mnemonico("Bloqueio: Alarme Configurável 2", "Evento", "Alarme", "EXABW"));
		lista.put("EXATB", new Mnemonico("Bloqueio: Alarme Configurável 3", "Evento", "Alarme", "EXATB"));
		lista.put("EXAFB", new Mnemonico("Bloqueio: Alarme Configurável 4", "Evento", "Alarme", "EXAFB"));
		lista.put("EXBBB", new Mnemonico("Bloqueio: Arrombamento de Baú ", "Evento", "Alarme", "EXBBB"));
		lista.put("EXRBB", new Mnemonico("Bloqueio: Bloqueio Remoto ", "Evento", "Alarme", "EXRBB"));
		lista.put("ANTLB", new Mnemonico("Bloqueio: Desconexão da antena GPS ", "Evento", "Alarme", "ANTLB"));
		lista.put("EXBTB", new Mnemonico("Bloqueio: Desconexão da Bateria do Veículo ", "Evento", "Alarme", "EXBTB"));
		lista.put("EXTMB", new Mnemonico("Bloqueio: Desconexão do Terminal do Rastreador ", "Evento", "Alarme", "EXTMB"));
		lista.put("TDENB", new Mnemonico("Bloqueio: Desengate de Carreta ", "Evento", "Alarme", "TDENB"));
		lista.put("EXTDB", new Mnemonico("Bloqueio: Desengate Não Autorizado de Carreta ", "Evento", "Alarme", "EXTDB"));
		lista.put("EXJMB", new Mnemonico("Bloqueio: Detecção de Presença do Jammer Celular ", "Evento", "Alarme", "EXJMB"));
		lista.put("MXDEB", new Mnemonico("Bloqueio: Distância Máxima Permitida Excedida ", "Evento", "Alarme", "MXDEB"));
		lista.put("TENB", new Mnemonico("Bloqueio: Engate de Carreta ", "Evento", "Alarme", "TENB"));
		lista.put("MXEEB", new Mnemonico("Bloqueio: Execuções no Mesmo Local Excedidas ", "Evento", "Alarme", "MXEEB"));
		lista.put("BCEVB", new Mnemonico("Bloqueio: Fechamento do Baú ", "Evento", "Alarme", "BCEVB"));
		lista.put("EXGPB", new Mnemonico("Bloqueio: GPS Inoperante ", "Evento", "Alarme", "EXGPB"));
		lista.put("IGBOF", new Mnemonico("Bloqueio: Ignição Desligada ", "Evento", "Alarme", "IGBOF"));
		lista.put("IGBON", new Mnemonico("Bloqueio: Ignição Ligada ", "Evento", "Alarme", "IGBON"));
		lista.put("ENUCB", new Mnemonico("Bloqueio: Motor Deslacrado via Comando Remoto ", "Evento", "Alarme", "ENUCB"));
		lista.put("ENUSB", new Mnemonico("Bloqueio: Motor Deslacrado via Terminal ", "Evento", "Alarme", "ENUSB"));
		lista.put("ENLCB", new Mnemonico("Bloqueio: Motor Lacrado via Comando Remoto ", "Evento", "Alarme", "ENLCB"));
		lista.put("ENSEB", new Mnemonico("Bloqueio: Motor Lacrado via Terminal ", "Evento", "Alarme", "ENSEB"));
		lista.put("ANSTB", new Mnemonico("Bloqueio: Parada Irregular ", "Evento", "Alarme", "ANSTB"));
		lista.put("ANMOB", new Mnemonico("Bloqueio: Partida Suspeita ", "Evento", "Alarme", "ANMOB"));
		lista.put("EXGLB", new Mnemonico("Bloqueio: Perda de GPS ", "Evento", "Alarme", "EXGLB"));
		lista.put("SMLSB", new Mnemonico("Bloqueio: Perda de Módulo Satélite ", "Evento", "Alarme", "SMLSB"));
		lista.put("RDOPB", new Mnemonico("Bloqueio: Porta Direita Aberta ", "Evento", "Alarme", "RDOPB"));
		lista.put("RDCLB", new Mnemonico("Bloqueio: Porta Direita Fechada ", "Evento", "Alarme", "RDCLB"));
		lista.put("LDOPB", new Mnemonico("Bloqueio: Porta Esquerda Aberta ", "Evento", "Alarme", "LDOPB"));
		lista.put("LDCLB", new Mnemonico("Bloqueio: Porta Esquerda Fechada ", "Evento", "Alarme", "LDCLB"));
		lista.put("EXBOB", new Mnemonico("Bloqueio: Tempo Excedido de Abertura de Baú ", "Evento", "Alarme", "EXBOB"));
		lista.put("MXTEB", new Mnemonico("Bloqueio: Tempo Máximo de Execução Excedido ", "Evento", "Alarme", "MXTEB"));
		lista.put("EXUPB", new Mnemonico("Bloqueio: Uso Indevido da Senha de Desbloqueio ", "Evento", "Alarme", "EXUPB"));
		lista.put("EXDPB", new Mnemonico("Bloqueio: Uso Indevido da Senha do Motorista ", "Evento", "Alarme", "EXDPB"));
		lista.put("EXSPB", new Mnemonico("Bloqueio: Uso Indevido da Senha do Supervisor ", "Evento", "Alarme", "EXSPB"));
		lista.put("SPDEB", new Mnemonico("Bloqueio: Velocidade Excedida ", "Evento", "Alarme", "SPDEB"));
		lista.put("BPANC", new Mnemonico("Botão de Pânico ", "Evento", "Alarme", "BPANC"));
		lista.put("IBT20", new Mnemonico("Carga da Bateria Interna: 20% ", "Evento", "Alarme", "IBT20"));
		lista.put("IBT30", new Mnemonico("Carga da Bateria Interna: 30% ", "Evento", "Alerta", "IBT30"));
		lista.put("TULKC", new Mnemonico("Carreta Deslacrada pela Central ", "Evento", "Alerta", "TULKC"));
		lista.put("TLKCT", new Mnemonico("Carreta Lacrada pela Central ", "Evento", "Alerta", "TLKCT"));
		lista.put("TLKDV", new Mnemonico("Carreta Lacrada pelo Motorista ", "Evento", "Alerta", "TLKDV"));
		lista.put("HSUNA", new Mnemonico("Cavalo Mecânico Ausente ", "Evento", "Normal", "HSUNA"));
		lista.put("HSAVA", new Mnemonico("Cavalo Mecânico Presente ", "Evento", "Normal", "HSAVA"));
		lista.put("VSACC", new Mnemonico("Compartilhamento de Sinal Aceito ", "Evento", "Alerta", "VSACC"));
		lista.put("PFSHA", new Mnemonico("Compartilhamento de Sinal Finalizado pelo Parceiro ", "Evento", "Alerta", "PFSHA"));
		lista.put("OFSHA", new Mnemonico("Compartilhamento de Sinal Finalizado pelo Proprietário do Veículo", "Evento", "Alerta", "OFSHA"));
		lista.put("RFSHA", new Mnemonico("Compartilhamento de Sinal Finalizado pelo Responsável pelo Sinal", "Evento", "Alerta", "RFSHA"));
		lista.put("CFSHA", new Mnemonico("Compartilhamento de Sinal Finalizado por Encerramento de Contrato", "Evento", "Alerta", "CFSHA"));
		lista.put("RESHA", new Mnemonico("Compartilhamento de Sinal Recusado ", "Evento", "Alerta", "RESHA"));
		lista.put("SATCG", new Mnemonico("Conexão de Módulo Satélite ", "Evento", "Alerta", "SATCG"));
		lista.put("SATCS", new Mnemonico("Conexão de Módulo Satélite ", "Evento", "Alerta", "SATCS"));
		lista.put("SATCG", new Mnemonico("Conexão de Módulo Satélite (em GPRS) ", "Evento", "Normal", "SATCG"));
		lista.put("SATCS", new Mnemonico("Conexão de Módulo Satélite (em Satélite) ", "Evento", "Normal", "SATCS"));
		lista.put("MSGRD", new Mnemonico("Confirmação de Leitura de Mensagem ", "Evento", "Normal", "MSGRD"));
		lista.put("CCANC", new Mnemonico("Contrato Cancelado no Rastreador ", "Evento", "Normal", "CCANC"));
		lista.put("CCANS", new Mnemonico("Contrato Cancelado pelo Sistema ", "Evento", "Alerta", "CCANS"));
		lista.put("ATDIS", new Mnemonico("Desabilitar antifurto ", "Comando ", "Normal", "ATDIS"));
		lista.put("DDSBL", new Mnemonico("Desativação pelo Motorista ", "Evento", "Alarme", "DDSBL"));
		lista.put("SDSBL", new Mnemonico("Desativação pelo Supervisor ", "Evento", "Alarme", "SDSBL"));
		lista.put("CTULK", new Mnemonico("Desbloqueio pela Central ", "Evento", "Normal", "CTULK"));
		lista.put("DULK", new Mnemonico("Desbloqueio pelo Motorista ", "Evento", "Alerta", "DULK"));
		lista.put("DLCKB", new Mnemonico("Desbloqueio Recusado: Baú Aberto ", "Evento", "Normal", "DLCKB"));
		lista.put("DLCKC", new Mnemonico("Desbloqueio Recusado: Carreta Desengatada ", "Evento", "Normal", "DLCKC"));
		lista.put("DLCKP", new Mnemonico("Desbloqueio Recusado: Porta de Cabine Aberta ", "Evento", "Normal", "DLCKP"));
		lista.put("ANTLS", new Mnemonico("Desconexão da antena GPS ", "Evento", "Alarme", "ANTLS"));
		lista.put("EXBTL", new Mnemonico("Desconexão da Bateria do Veículo ", "Evento", "Alarme", "EXBTL"));
		lista.put("EXTML", new Mnemonico("Desconexão do Terminal do Rastreador ", "Evento", "Alarme", "EXTML"));
		lista.put("TDENG", new Mnemonico("Desengate de Carreta ", "Evento", "Normal", "TDENG"));
		lista.put("EXTDU", new Mnemonico("Desengate Não Autorizado de Carreta ", "Evento", "Alarme", "EXTDU"));
		lista.put("JMMOF", new Mnemonico("Desligamento do Jammer Celular ", "Evento", "Normal", "JMMOF"));
		lista.put("FTOFF", new Mnemonico("Desligamento do Primeiro Rastreador ", "Evento", "Alarme", "FTOFF"));
		lista.put("EXJMA", new Mnemonico("Detecção de Presença do Jammer Celular ", "Evento", "Normal", "EXJMA"));
		lista.put("MXDEX", new Mnemonico("Distância Máxima Permitida Excedida ", "Evento", "Normal", "MXDEX"));
		lista.put("TENG", new Mnemonico("Engate de Carreta ", "Evento", "Normal", "TENG"));
		lista.put("FEIN", new Mnemonico("Entrada em Cerca ", "Evento", "Normal", "FEIN"));
		lista.put("RTIN", new Mnemonico("Entrada em Rota ", "Evento", "Normal", "RTIN"));
		lista.put("UNKEV", new Mnemonico("Evento Desconhecido", "Evento", "Normal", "UNKEV"));
		lista.put("MACRO", new Mnemonico("Execução de Macro ", "Evento", " Mensagem ", "MACRO"));
		lista.put("MXEEX", new Mnemonico("Execuções no mesmo local Excedidas ", "Evento", "Normal", "MXEEX"));
		lista.put("TSNK1", new Mnemonico("Falha detectada no Sensor de Temperatura 1 ", "Evento", "Alerta", "TSNK1"));
		lista.put("TSNK2", new Mnemonico("Falha detectada no Sensor de Temperatura 2 ", "Evento", "Alerta", "TSNK2"));
		lista.put("TSNK3", new Mnemonico("Falha detectada no Sensor de Temperatura 3 ", "Evento", "Alerta", "TSNK3"));
		lista.put("TSNK4", new Mnemonico("Falha detectada no Sensor de Temperatura 4 ", "Evento", "Alerta", "TSNK4"));
		lista.put("TSNK5", new Mnemonico("Falha detectada no Sensor de Temperatura 5 ", "Evento", "Alerta", "TSNK5"));
		lista.put("NFAIL", new Mnemonico("Falha na Bateria Interna do Rastreador ", "Evento", "Alarme", "NFAIL"));
		lista.put("BLKFD", new Mnemonico("Falha no Fechamento da Trava de Baú ", "Evento", "Alarme", "BLKFD"));
		lista.put("ODOMF", new Mnemonico("Falha no Odômetro - Calculando Valores pelo GPS ", "Evento", "Normal", "ODOMF"));
		lista.put("RDCLD", new Mnemonico("Fechamento de Porta Direita ", "Evento", "Normal", "RDCLD"));
		lista.put("LDCLD", new Mnemonico("Fechamento de Porta Esquerda ", "Evento", "Normal", "LDCLD"));
		lista.put("DCIOF", new Mnemonico("Fechamento de Portas ", "Evento", "Normal", "DCIOF"));
		lista.put("BCEVT", new Mnemonico("Fechamento do Baú ", "Evento", "Normal", "BCEVT"));
		lista.put("MOVFN", new Mnemonico("Fim de Movimentação ", "Evento", "Normal", "MOVFN"));
		lista.put("EXGPO", new Mnemonico("GPS Inoperante ", "Evento", "Alarme", "EXGPO"));
		lista.put("ATENA", new Mnemonico("Habilitar Antifurto ", "Comando ", "Normal", "ATENA"));
		lista.put("IGNOF", new Mnemonico("Ignição Desligada ", "Evento", "Normal", "IGNOF"));
		lista.put("IGNON", new Mnemonico("Ignição Ligada ", "Evento", "Normal", "IGNON"));
		lista.put("HEACO", new Mnemonico("Impacto Frontal/Traseiro ", "Evento", "Alarme", "HEACO"));
		lista.put("SIDCO", new Mnemonico("Impacto Lateral ", "Evento", "Alarme", "SIDCO"));
		lista.put("REACO", new Mnemonico("Impacto Vertical/Traseiro ", "Evento", "Alarme", "REACO"));
		lista.put("MOVST", new Mnemonico("Início de Movimentação ", "Evento", "Normal", "MOVST"));
		lista.put("BENSM", new Mnemonico("Início do Modo Economia de Energia ", "Evento", "Normal", "BENSM"));
		lista.put("HIBEM", new Mnemonico("Início do Modo Hibernação ", "Evento", "Normal", "HIBEM"));
		lista.put("RESTM", new Mnemonico("Início do Modo Repouso ", "Evento", "Normal", "RESTM"));
		lista.put("JMMON", new Mnemonico("Jammer Celular Ativo ", "Evento", "Normal", "JMMON"));
		lista.put("DRLGN", new Mnemonico("Login do Motorista ", "Evento", "Normal", "DRLGN"));
		lista.put("PNLGN", new Mnemonico("Login sob Senha de Pânico ", "Evento", "Alarme", "PNLGN"));
		lista.put("DRLOF", new Mnemonico("Logoff do Motorista ", "Evento", "Normal", "DRLOF"));
		lista.put("TXMSG", new Mnemonico("Mensagem de Texto ", "Comando", "Normal", "TXMSG"));
		lista.put("BTHON", new Mnemonico("Módulo Bluetooth Conectado ", "Evento", "Normal", "BTHON"));
		lista.put("BTHOF", new Mnemonico("Módulo Bluetooth Desconectado ", "Evento", "Normal", "BTHOF"));
		lista.put("SATIN", new Mnemonico("Módulo Satélite Instalado ", "Evento", "Alerta", "SATIN"));
		lista.put("SATRE", new Mnemonico("Módulo Satélite Removido ", "Evento", "Alerta", "SATRE"));
		lista.put("ENUSD", new Mnemonico("Motor deslacrado devido à desativação ", "Evento", "Normal", "ENUSD"));
		lista.put("ENUCR", new Mnemonico("Motor Deslacrado via Comando Remoto", "Evento", "Normal", "ENUCR"));
		lista.put("ENUST", new Mnemonico("Motor Deslacrado via Terminal ", "Evento", "Normal", "ENUST"));
		lista.put("ENLCR", new Mnemonico("Motor Lacrado via Comando remoto ", "Evento", "Normal", "ENLCR"));
		lista.put("ENSET", new Mnemonico("Motor Lacrado via Terminal ", "Evento", "Normal", "ENSET"));
		lista.put("UNKDR", new Mnemonico("Motorista Desconhecido ", "Evento", "Alerta", "UNKDR"));
		lista.put("MVDTC", new Mnemonico("Movimentação Detectada ", "Evento", "Evento", "MVDTC"));
		lista.put("STDTC", new Mnemonico("Parada Detectada ", "Evento", "Evento", "STDTC"));
		lista.put("ANSTP", new Mnemonico("Parada Irregular ", "Evento", "Normal", "ANSTP"));
		lista.put("ANMOV", new Mnemonico("Partida Suspeita ", "Evento", "Normal", "ANMOV"));
		lista.put("FETHR", new Mnemonico("Passagem por Cerca ", "Evento", "Normal", "FETHR"));
		lista.put("EXGPL", new Mnemonico("Perda de GPS ", "Evento", "Alarme", "EXGPL"));
		lista.put("SMLST", new Mnemonico("Perda de Módulo Satélite ", "Evento", "Normal", "SMLST"));
		lista.put("SIGLO", new Mnemonico("Perda de Sinal ", "Evento", "Alerta", "SIGLO"));
		lista.put("SIGLO", new Mnemonico("Perda de Sinal Celular ", "Evento", "Alerta", "SIGLO"));
		lista.put("SILOS", new Mnemonico("Perda de Sinal Satélite ", "Evento", "Alerta", "SILOS"));
		lista.put("RDOPN", new Mnemonico("Porta Direita Aberta ", "Evento", "Normal", "RDOPN"));
		lista.put("RDCLD", new Mnemonico("Porta Direita Fechada ", "Evento", "Normal", "RDCLD"));
		lista.put("LDOPN", new Mnemonico("Porta Esquerda Aberta ", "Evento", "Normal", "LDOPN"));
		lista.put("LDCLD", new Mnemonico("Porta Esquerda Fechada ", "Evento", "Normal", "LDCLD"));
		lista.put("PAUTO", new Mnemonico("Posição Automática", "Evento", "Normal", "PAUTO"));
		lista.put("PSPR", new Mnemonico("Posição Avulsa ", "Evento", "Normal", "PSPR"));
		lista.put("TTRDT", new Mnemonico("Rastreador do Cavalo Detectado ", "Evento", "Alerta", "TTRDT"));
		lista.put("SCTTR", new Mnemonico("Rastreador Respondeu ao Teste de Comunicação Satélite Efetuado", "Evento", "Alerta", "SCTTR"));
		lista.put("FEOUT", new Mnemonico("Saída de Cerca ", "Evento", "Normal", "FEOUT"));
		lista.put("RTOUT", new Mnemonico("Saída de Rota ", "Evento", "Normal", "RTOUT"));
		lista.put("PMOEX", new Mnemonico("Saída do Modo Pânico ", "Evento", "Evento", "PMOEX"));
		lista.put("PPANC", new Mnemonico("Senha de Pânico ", "Evento", "Alerta", "PPANC"));
		lista.put("TSOK1", new Mnemonico("Sensor de Temperatura 1 se recuperou da Falha ", "Evento", "Alerta", "TSOK1"));
		lista.put("TSOK2", new Mnemonico("Sensor de Temperatura 2 se recuperou da Falha ", "Evento", "Alerta", "TSOK2"));
		lista.put("TSOK3", new Mnemonico("Sensor de Temperatura 3 se recuperou da Falha ", "Evento", "Alerta", "TSOK3"));
		lista.put("TSOK4", new Mnemonico("Sensor de Temperatura 4 se recuperou da Falha ", "Evento", "Alerta", "TSOK4"));
		lista.put("TSOK5", new Mnemonico("Sensor de Temperatura 5 se recuperou da Falha ", "Evento", "Alerta", "TSOK5"));
		lista.put("BOREQ", new Mnemonico("Solicitação de Abertura de Baú ", "Evento", " Solicitação de Autorização ", "BOREQ"));
		lista.put("BORIN", new Mnemonico("Solicitação de Abertura de Baú por Ocorrência ", "Evento", " Solicitação de Autorização ", "BORIN"));
		lista.put("BOREP", new Mnemonico("Solicitação de Abertura do Baú sob Senha de Pânico ", "Evento", " Solicitação de Autorização ", "BOREP"));
		lista.put("VSREQ", new Mnemonico("Solicitação de Compartilhamento de Sinal ", "Evento", " Solicitação de Autorização ", "VSREQ"));
		lista.put("ULKIN", new Mnemonico("Solicitação de Desbloqueio por Ocorrência ", "Evento", " Solicitação de Autorização ", "ULKIN"));
		lista.put("EULK", new Mnemonico("Solicitação de Deslacre de Motor ", "Comando ", "Normal", "EULK"));
		lista.put("EULIN", new Mnemonico("Solicitação de Deslacre de Motor por Ocorrência ", "Evento", " Solicitação de Autorização ", "EULIN"));
		lista.put("EULP", new Mnemonico("Solicitação de Deslacre do Motor sob Senha de Pânico ", "Evento", " Solicitação de Autorização ", "EULP"));
		lista.put("MEREQ", new Mnemonico("Solicitação de Execução de Macro ", "Evento", " Solicitação de Autorização ", "MEREQ"));
		lista.put("MEREQ", new Mnemonico("Solicitação de Execução de Macro ", "Evento", " Solicitação ", "MEREQ"));
		lista.put("MACIN", new Mnemonico("Solicitação de Execução de Macro por Ocorrência ", "Evento", " Solicitação de Autorização ", "MACIN"));
		lista.put("MEREP", new Mnemonico("Solicitação de Execução de Macro Sob Pânico ", "Evento", " Solicitação de Autorização ", "MEREP"));
		lista.put("TPLO1", new Mnemonico("Temperatura 1 Abaixo da Mínima configurada ", "Evento", "Alerta", "TPLO1"));
		lista.put("TPHI1", new Mnemonico("Temperatura 1 Acima da Máxima configurada ", "Evento", "Alerta", "TPHI1"));
		lista.put("TPOK1", new Mnemonico("Temperatura 1 Voltou ao Normal", "Evento", "Normal", "TPOK1"));
		lista.put("TPLO2", new Mnemonico("Temperatura 2 Abaixo da Mínima configurada ", "Evento", "Alerta", "TPLO2"));
		lista.put("TPHI2", new Mnemonico("Temperatura 2 Acima da Máxima configurada ", "Evento", "Alerta", "TPHI2"));
		lista.put("TPOK2", new Mnemonico("Temperatura 2 Voltou ao Normal", "Evento", "Normal", "TPOK2"));
		lista.put("TPLO3", new Mnemonico("Temperatura 3 Abaixo da Mínima configurada ", "Evento", "Alerta", "TPLO3"));
		lista.put("TPHI3", new Mnemonico("Temperatura 3 Acima da Máxima configurada ", "Evento", "Alerta", "TPHI3"));
		lista.put("TPOK3", new Mnemonico("Temperatura 3 Voltou ao Normal", "Evento", "Normal", "TPOK3"));
		lista.put("TPLO4", new Mnemonico("Temperatura 4 Abaixo da Mínima configurada ", "Evento", "Alerta", "TPLO4"));
		lista.put("TPHI4", new Mnemonico("Temperatura 4 Acima da Máxima configurada ", "Evento", "Alerta", "TPHI4"));
		lista.put("TPOK4", new Mnemonico("Temperatura 4 Voltou ao Normal", "Evento", "Normal", "TPOK4"));
		lista.put("TPLO5", new Mnemonico("Temperatura 5 Abaixo da Mínima configurada ", "Evento", "Alerta", "TPLO5"));
		lista.put("TPHI5", new Mnemonico("Temperatura 5 Acima da Máxima configurada ", "Evento", "Alerta", "TPHI5"));
		lista.put("TPOK5", new Mnemonico("Temperatura 5 Voltou ao Normal", "Evento", "Normal", "TPOK5"));
		lista.put("TPREQ", new Mnemonico("Temperatura Avulsa ", "Evento", "Normal", "TPREQ"));
		lista.put("SCTTE", new Mnemonico("Tempo de resposta excedido para Teste de Comunicação Satélite", "Evento", "Alerta", "SCTTE"));
		lista.put("EXBOE", new Mnemonico("Tempo Excedido de Abertura de Baú ", "Evento", "Alarme", "EXBOE"));
		lista.put("MXTEX", new Mnemonico("Tempo Máximo de Execução Excedido ", "Evento", "Alerta", "MXTEX"));
		lista.put("MRTSD", new Mnemonico("Tentativas Esgotadas para Envio de Comando", "Evento", "Alerta", "MRTSD"));
		lista.put("TCOMM", new Mnemonico("Teste Comunicação ", "Evento", "Normal", "TCOMM"));
		lista.put("ITCOM", new Mnemonico("Teste de Antena Satélite ", "Evento", "Normal", "ITCOM"));
		lista.put("ACTTS", new Mnemonico("Teste de Comunicação Satelital ", "Evento", "Normal", "ACTTS"));
		lista.put("5WLCK", new Mnemonico("Trava de 5ª Roda Fechada ", "Evento", "Normal", "5WLCK"));
		lista.put("5WUKR", new Mnemonico("Trava de 5ª Roda Liberada via Comando Remoto", "Evento", "Normal", "5WUKR"));
		lista.put("5WUKT", new Mnemonico("Trava de 5ª Roda Liberada via Terminal ", "Evento", "Normal", "5WUKT"));
		lista.put("BLOTT", new Mnemonico("Trava de Baú aberta pelo Rastreador do Cavalo ", "Evento", "Alerta", "BLOTT"));
		lista.put("EXUPE", new Mnemonico("Uso Indevido da Senha de Desbloqueio ", "Evento", "Alarme", "EXUPE"));
		lista.put("EXDPE", new Mnemonico("Uso Indevido da Senha do Motorista ", "Evento", "Alarme", "EXDPE"));
		lista.put("EXSPE", new Mnemonico("Uso Indevido da Senha do Supervisor ", "Evento", "Alarme", "EXSPE"));
		lista.put("VULKC", new Mnemonico("Veículo Deslacrado pela Central ", "Evento", "Alerta", "VULKC"));
		lista.put("VLKCT", new Mnemonico("Veículo Lacrado pela Central ", "Evento", "Alerta", "VLKCT"));
		lista.put("VLKDV", new Mnemonico("Veículo Lacrado pelo Motorista ", "Evento", "Alerta", "VLKDV"));
		lista.put("VSIGO", new Mnemonico("Veículo Parado com Ignição Ligada ", "Evento", "Evento", "VSIGO"));
		lista.put("SPDEX", new Mnemonico("Velocidade Excedida ", "Evento", "Alerta", "SPDEX"));
		lista.put("NRSPD", new Mnemonico("Velocidade Normalizada", "Evento", "Normal", "NRSPD"));
		lista.put("TOPEN", new Mnemonico("Violação da Caixa do Rastreador ", "Evento", "Alarme", "TOPEN"));
		lista.put("TRIVD", new Mnemonico("Violação da Instalação do Rastreador de Carreta ", "Evento", "Alarme", "TRIVD"));
		lista.put("VEPAV", new Mnemonico("Violação de Painel do Veículo ", "Evento", "Alarme", "VEPAV"));
		lista.put("BLKVD", new Mnemonico("Violação do Pino da Trava de Baú ", "Evento", "Alarme", "BLKVD"));
		lista.put("DOORL", new Mnemonico("Portas Travadas ", "Evento", "Normal", "DOORL"));
		lista.put("DOORU", new Mnemonico("Portas Destravadas ", "Evento", "Normal", "DOORU"));
		lista.put("BOOKC", new Mnemonico("Reserva Fechada ", "Evento", "Normal", "BOOKC"));
		
		//criar tabela de comandos para tratar os casos abaixo:
		lista.put("EGNLK", new Mnemonico("Lacrar Motor", "Normal", "Normal", "EGNLK"));
		lista.put("BIP", new Mnemonico("Emitir Bip de Sirene", "Normal", "Normal", "BIP"));
		
		
	}
	
}
